---

# This is the string configuration file for English.
en-GB: &flag-en
    # Triggers
    trigger_action_name_ap_random: "AP: Random"
    trigger_action_description_ap_random: "Sets a counter to a random number in a range using the AP seed."
    trigger_action_readable_ap_random: "Counter {0}: Set to a random number between {1} and {2} (inclusive)."

    trigger_action_name_ap_item_check: "AP: Item Check"
    trigger_action_description_ap_item_check: "Checks for the existence of AP items."
    trigger_action_readable_ap_item_check: "Checks for the existence of AP items."

    trigger_action_name_ap_victory: "AP: Victory"
    trigger_action_description_ap_victory: "Claims AP Victory. Should be used by final levels only!"
    trigger_action_readable_ap_victory: "Claim AP Victory."

    trigger_action_name_ap_export: "AP: Export"
    trigger_action_description_ap_export: "Export your map with a debug seed, to a .lua file so it may be imported into the campaign."
    trigger_action_readable_ap_export: "Export Your Map with debug seed {0}. Map Name {1}. Author {2}. Side Objective {3}. Side Objective {4}. Side Objective {5}. Main Objective {6}"

    trigger_action_name_ap_import: "AP: Import"
    trigger_action_description_ap_import: "Import a built-in map."
    trigger_action_readable_ap_import: "Import Map ID {0}."

    trigger_action_name_ap_count_item: "AP: Count Item"
    trigger_action_description_ap_count_item: "Counts AP items."
    trigger_action_readable_ap_count_item: "Add AP count item {0} and store into {1}."

    trigger_action_name_ap_location_send: "AP: Check Location"
    trigger_action_description_ap_location_send: "Checks an AP location."
    trigger_action_readable_ap_location_send: "Check AP location ID {0}"

    trigger_action_name_ap_prng_seed_num: "AP: Set Seed ID"
    trigger_action_description_ap_prng_seed_num: "Sets the AP seed ID of this map. Will be used by the importer map. Useful for debugging various seeds."
    trigger_action_readable_ap_prng_seed_num: "Set AP seed ID to {0}."

    trigger_condition_name_ap_has_item: "AP: Has Item"
    trigger_condition_description_ap_has_item: "Triggers if a certain AP item is above a count."
    trigger_condition_readable_ap_has_item: "AP item count of {0} and is {2} the expected count of {1}."

    trigger_action_name_unit_random_teleport: "AP: Unit: Random Teleport"
    trigger_action_description_unit_random_teleport: "Teleports a unit from one location to another in a random spot. Uses the AP random seed."
    trigger_action_readable_unit_random_teleport: "Teleport all {0} owned by {1} from {2} to a random spot in {3} (silent \u003d {4})."

    trigger_action_name_location_unit_random_teleport: "Location: Random Teleport to Unit"
    trigger_action_description_location_unit_random_teleport: "Teleports a location to a random unit."
    trigger_action_readable_location_unit_random_teleport: "Randomly Move location {0} to {1} owned by {2} at {3}."

    trigger_action_name_ap_spawn_unit: "AP: Spawn Unit"
    trigger_action_description_ap_spawn_unit: "Spawns a unit or structure somewhere on the map for a specific player. Randomization uses the AP seed."
    trigger_action_readable_ap_spawn_unit: "Spawn {5} {0} with colour variation {7} at {1} for {2} facing {8} (silent = {3}, no delay = {4}, AP random location = {6})."

    unit_description_barracks_ap: "Used to recruit new ground units. Can also reinforce injured units."
    unit_description_port_ap: "Used to recruit new water units. Can also reinforce injured units."
    unit_description_tower_ap: "Used to recruit new air units. Can also reinforce injured units."
    unit_description_hideout_ap: "Used to recruit Thief and Rifleman units. Can also reinforce injured units."

    trigger_action_name_map_randomize: "AP: Generate Map"
    trigger_action_description_map_randomize: "Randomly generates a map in the location specified."
    trigger_action_readable_map_randomize: "Generate Terrain at {0} with a scale of {1}.\nHas Symmetry: {2}\nArchipelago Weight (0-100): {3}\nOcean Weight (0-100): {4}\nLand Weight (0-100): {5}\nForest/Road Weight (0-100): {6}\nIndoor Weight (0-100): {7}\nRiver Weight (0-100): {8}"
    trigger_action_name_position_randomize: "AP: Place Structures Symmetric"
    trigger_action_description_position_randomize: "Randomly generates structures on the whole map for each player with symmetry."
    trigger_action_readable_position_randomize: "Place symmetric structures that have a Structure Gap: {0}, Strongholds: {1}, Barracks: {2}, Towers: {3}, Hideouts: {4}, Ports: {5}, Player Villages: {6}, Neutral Villages: {7}, Neutral Production: {8}"
    trigger_action_name_position_asymmetric_randomize: "AP: Place Structures Asymmetric"
    trigger_action_description_position_asymmetric_randomize: "Randomly generates structures on the whole map for each player without symmetry."
    trigger_action_readable_position_asymmetric_randomize: "Place asymmetric structures that have a Structure Gap: {0}, Strongholds: {1}, Barracks: {2}, Towers: {3}, Hideouts: {4}, Ports: {5}, Player Villages: {6}, Neutral Villages: {7}, Neutral Production: {8}"

    # Verbs
    ui_unit_verbs_mw_sacrifice: "Sacrifice"
    ui_unit_verbs_mw_summon: "Summon"

    # Units
    structure_name_tower_ap: "AP Tower"
    structure_name_barracks_ap: "AP Barracks"
    structure_name_hideout_ap: "AP Hideout"
    structure_name_port_ap: "AP Port"

    # Custom Commanders

    #Duchess
    character_duchess_name: "Sabah"
    character_duchess_title: "The Duchess of Dorne"
    unit_description_commander_duchess: "Duchess of Dorne. She can make her units stand guard."

    groove_name_morale_boost: "En Garde"
    groove_description_morale_boost: "Friendly units within 2 tiles strike first when attacked."
    groove_name_all_caps_groove_morale_boost: "EN GARDE"


    mini_groove_name_split: "RÃ©organiser"

    # CUTSCENE DUCHESS VOICE LINES
    ui_cutscene_shout_duchess_acoldwindblows: "\"A cold wind blows!\""
    ui_cutscene_shout_duchess_astormapproaches: "\"A storm approaches!\""
    ui_cutscene_shout_duchess_attack2: "Pained Grunt"
    ui_cutscene_shout_duchess_attack3: "Grunt of Exertion"
    ui_cutscene_shout_duchess_attack4: "Frustrated Grunt"
    ui_cutscene_shout_duchess_ihavefailed: "\"I have failed.\""
    ui_cutscene_shout_duchess_illmakethisquick: "\"I'll make this quick.\""
    ui_cutscene_shout_duchess_imnotheretoplay: "\"I am not here to play.\""
    ui_cutscene_shout_duchess_hit1: "Shocked Cry"
    ui_cutscene_shout_duchess_hit2: "Angry Grunt"
    ui_cutscene_shout_duchess_hit3: "Shocked Grunt"
    ui_cutscene_shout_duchess_powerofthetempest: "\"Power of the tempest!\""
    ui_cutscene_shout_duchess_theresnotimetowaste: "\"There's no time to...\""
    ui_cutscene_shout_duchess_thewindrises: "\"The wind rises!\""
    ui_cutscene_shout_duchess_absolutelynot: "\"Absolutely not.\""
    ui_cutscene_shout_duchess_agreed: "\"Agreed.\""
    ui_cutscene_shout_duchess_fallback: "\"Fall back!\""
    ui_cutscene_shout_duchess_farewell: "\"Farewell.\""
    ui_cutscene_shout_duchess_getoutofmysight: "\"Get out of my sight!\""
    ui_cutscene_shout_duchess_greetings: "\"Greetings.\""
    ui_cutscene_shout_duchess_hmph: "\"Hmph.\""
    ui_cutscene_shout_duchess_howtimeflies: "\"How time flies.\""
    ui_cutscene_shout_duchess_itireofyourpresence: "\"I tire of your presence.\""
    ui_cutscene_shout_duchess_koji1: "Angry \"Koji!\""
    ui_cutscene_shout_duchess_koji2: "Fearful \"Koji!\""
    ui_cutscene_shout_duchess_laugh1: "Laugh"
    ui_cutscene_shout_duchess_laugh2: "Chuckle"
    ui_cutscene_shout_duchess_no: "\"No.\""
    ui_cutscene_shout_duchess_noonethreatensmypeople: "\"No one threatens my people.\""
    ui_cutscene_shout_duchess_sigh: "Sigh"
    ui_cutscene_shout_duchess_standdown: "\"Stand down!\""
    ui_cutscene_shout_duchess_stopthis: "\"Stop this!\""
    ui_cutscene_shout_duchess_victoryshallbeswift: "\"Victory shall be swift.\""
    ui_cutscene_shout_duchess_weareoldfriends: "\"We are old friends.\""
    ui_cutscene_shout_duchess_westandtogether: "\"We stand together.\""
    ui_cutscene_shout_duchess_whatisthis1: "\"What is this?\""
    ui_cutscene_shout_duchess_yes: "\"Yes.\""
    ui_cutscene_shout_duchess_youfiend: "\"You fiend!\""
    ui_cutscene_shout_duchess_youhavemythanks: "\"You have my thanks.\""
    ui_cutscene_shout_duchess_youthinkthisisagame: "\"You think this is a game?\""

de-DE: *flag-en
es-ES: *flag-en
fr-FR: *flag-en
it-IT: *flag-en
ja-JP: *flag-en
ko-KR: *flag-en
pt-BR: *flag-en
ru-RU: *flag-en
zh-Hans: *flag-en
zh-Hant: *flag-en
...