---

unitClasses:
  - id: hideout_ap
    name: structure_name_hideout_ap
    aiPriority: 4.0
    verbs:
      - recruit_ap
    battleUnitCount: 1
    isStructure: true
    garrisonUnit: garrison
    canReinforce: true
    canBeReinforced: false
    canBeCaptured: true
    isNeutraliseable: true
    damageMultiplier: 1
    movement: land_building
    income: 0
    cost: 500
    recruitTags: [type.ground.hideout]
    regeneration: 10
    tags:
      - structure
    sightRange: 1
      
units:
  - class: hideout_ap
    faction: neutral
    name: structure_name_hideout_ap
    mapAnimation: structures/hideout
    mapLightSource:
      sprite: lights_large
      scale: [1.0, 1.0]
      jitter:
        scale: 1.0
        frequency: 0.3
        frequencyVariance: 0.15
    battleLightSource:
      sprite: lights_battle_medium
      scale: [0.8, 0.8]
      jitter:
        scale: 0.33
        frequency: 0.3
        frequencyVariance: 0.15
    smallPortrait: portraits/small/portrait_structure_small.png
    mediumPortrait: portraits/medium/hideout.png
    grabPos: [14, 7]
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie
    structureImage:
      spriteSheet: backgrounds/hideout/hideout_background_full
      farBackground: hideout_background_full_background_2
      nearBackground: hideout_background_full_background_1
      foreground: hideout_background_full_foreground
      keeperPosition: [74, 85]
      leftBannerOffset: [-16, 7]
      rightBannerOffset: [-9, 4]
...